language: node_js
node_js: '12'
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn global add gulp-cli
script:
  - gulp build
  - if (branch = master) AND (type != pull_request )
    gulp
